const products = [
  {
    id: 1,
    href: "/product/1",
    title: "The Unicorn",
    description: "They exist!",
    price: "9.99",
    imgSrc: "box_cat.png",
  },
  {
    id: 2,
    href: "/product/2",
    title: "The Mermaid",
    description: "Mythical beauty",
    price: "12.99",
    imgSrc: "cat_love.png",
  },
  {
    id: 3,
    href: "/product/3",
    title: "The Dragon",
    description: "Fierce and majestic",
    price: "14.99",
    imgSrc: "chattering_cat.png",
  },
  {
    id: 4,
    href: "/product/4",
    title: "The Pegasus",
    description: "Winged wonder",
    price: "11.99",
    imgSrc: "cool_cat.png",
  },
  {
    id: 5,
    href: "/product/5",
    title: "The Kraken",
    description: "Tentacled terror",
    price: "16.99",
    imgSrc: "cute_cat.png",
  },
  {
    id: 6,
    href: "/product/6",
    title: "The Minotaur",
    description: "Half-man, half-bull",
    price: "13.99",
    imgSrc: "eat_cat.png",
  },
  {
    id: 7,
    href: "/product/7",
    title: "The Chimera",
    description: "A monstrous mix",
    price: "15.99",
    imgSrc: "fish_cat.png",
  },
  {
    id: 8,
    href: "/product/8",
    title: "The Sphinx",
    description: "Riddle me this",
    price: "10.99",
    imgSrc: "flying_cat.png",
  },
  {
    id: 9,
    href: "/product/9",
    title: "The Kraken 2",
    description: "Another tentacled terror",
    price: "18.99",
    imgSrc: "playing_cat.png",
  },
  {
    id: 10,
    href: "product/10",
    title: "The Leviathan",
    description: "Whale of a tale",
    price: "17.99",
    imgSrc: "sitting_cat.png",
  },
];

export default products;